
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: manual_approval
on:
  workflow_dispatch:
jobs:
  ask-now:
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    timeout-minutes: 10
    with:
      instructions: Approve or reject this manual approval task.
      approvers:  AutoTest.61a8b798-cd93-431c-abe3-7ea81d482e7f.PendingTasksCaseB
      debug: true